# Generated by Django 3.2.25 on 2024-12-14 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistencia_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='feito_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='assistencia_tecnica.indicador'),
        ),
        migrations.AddField(
            model_name='fichaassistenciatecnica',
            name='unidades_sanitaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='assistencia_tecnica.unidadesanitaria'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='assistencia_tecnica.provincia'),
        ),
        migrations.AddField(
            model_name='area',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='assistencia_tecnica.sector'),
        ),
    ]
