# Generated by Django 3.2.25 on 2024-12-14 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='feito_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.instrumento'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.sector'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='feito_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.instrumento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.sector'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='si_stock.provincia'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='si_stock.sector'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='feito_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.instrumento'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.provincia'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.sector'),
        ),
        migrations.AddField(
            model_name='aprovacao',
            name='feito_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aprovacao',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si_stock.requisicao'),
        ),
    ]
